### POST request too create a new entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "jon doe with billing account" ,
  "email": "test@example3" ,
  "address" : "290 main street",
  "registeredDate": "2024-11-21",
  "dateOfBirth": "1998-09-09"
}

###