version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: patient-service-db

    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

    ports:
      - "5000:5432"

    volumes:
      - ./db_volumes/postgres:/var/lib/postgresql/data

    networks:
      - internal

  patient-service:
    build: .

    container_name: patient-service

    ports:
      - "4000:4000"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password

    networks:
      - internal

networks:
  internal: