### POST request too create a new entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name" : "jon doe with billing account and kafka message" ,
  "email": "test46@exap8dfdfd098" ,
  "address" : "290 main street",
  "registeredDate": "2026-05-21",
  "dateOfBirth": "1998-09-06"
}

###